image: registry.gitlab.com/aboutbits/docker-inside-docker:19

services:
  - docker:19-dind

stages:
  - setup
  - deploy

cache:
  paths:
    - node_modules

before_script:
  - docker network create proxy

setup:
  stage: setup
  script:
    - docker-compose run --rm -T node npm ci

deploy:
 stage: deploy
 only:
   - master
 script:
   - docker-compose run --rm -T node npm run deploy -- --scope=${VERCEL_SCOPE} --token=${VERCEL_TOKEN}
