version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    command: npm run dev
    networks:
      - internal
      - proxy
    labels:
      - traefik.frontend.rule=Host:web.aboutbits.local
      - traefik.docker.network=proxy
      - traefik.port=3000
      - traefik.backend=pwa-boilerplate-web

networks:
  proxy:
    external: true
  internal:
    external: false
